// Generated by OABuilder
package test.xice.tsam.model.oa.propertypath;
 
import java.io.Serializable;

import test.xice.tsam.model.oa.Developer;
import test.xice.tsam.model.oa.propertypath.ApplicationTypePPx;
import test.xice.tsam.model.oa.propertypath.PPxInterface;

import test.xice.tsam.model.oa.*;
 
public class DeveloperPPx implements PPxInterface, Serializable {
    private static final long serialVersionUID = 1L;
    public final String pp;  // propertyPath
     
    public DeveloperPPx(String name) {
        this(null, name);
    }

    public DeveloperPPx(PPxInterface parent, String name) {
        String s = null;
        if (parent != null) {
            s = parent.toString();
        }
        if (s == null) s = "";
        if (name != null && name.length() > 0) {
            if (s.length() > 0 && name.charAt(0) != ':') s += ".";
            s += name;
        }
        pp = s;
    }

    public ApplicationTypePPx applicationTypes() {
        ApplicationTypePPx ppx = new ApplicationTypePPx(this, Developer.P_ApplicationTypes);
        return ppx;
    }

    public String id() {
        return pp + "." + Developer.P_Id;
    }

    public String created() {
        return pp + "." + Developer.P_Created;
    }

    public String firstName() {
        return pp + "." + Developer.P_FirstName;
    }

    public String lastName() {
        return pp + "." + Developer.P_LastName;
    }

    public String inactiveDate() {
        return pp + "." + Developer.P_InactiveDate;
    }

    public String fullName() {
        return pp + "." + Developer.P_FullName;
    }

    @Override
    public String toString() {
        return pp;
    }
}
 
