// Generated by OABuilder
package test.xice.tsac.model.oa.propertypath;
 
import test.xice.tsac.model.oa.*;
 
public class RCServiceListDetailPP {
    private static ApplicationTypePPx applicationType;
    private static RCServiceListPPx rcServiceList;
     

    public static ApplicationTypePPx applicationType() {
        if (applicationType == null) applicationType = new ApplicationTypePPx(RCServiceListDetail.P_ApplicationType);
        return applicationType;
    }

    public static RCServiceListPPx rcServiceList() {
        if (rcServiceList == null) rcServiceList = new RCServiceListPPx(RCServiceListDetail.P_RCServiceList);
        return rcServiceList;
    }

    public static String id() {
        String s = RCServiceListDetail.P_Id;
        return s;
    }

    public static String name() {
        String s = RCServiceListDetail.P_Name;
        return s;
    }

    public static String login() {
        String s = RCServiceListDetail.P_Login;
        return s;
    }

    public static String packages() {
        String s = RCServiceListDetail.P_Packages;
        return s;
    }

    public static String type() {
        String s = RCServiceListDetail.P_Type;
        return s;
    }

    public static String baseDirectory() {
        String s = RCServiceListDetail.P_BaseDirectory;
        return s;
    }

    public static String startCommand() {
        String s = RCServiceListDetail.P_StartCommand;
        return s;
    }

    public static String stopCommand() {
        String s = RCServiceListDetail.P_StopCommand;
        return s;
    }

    public static String healthPort() {
        String s = RCServiceListDetail.P_HealthPort;
        return s;
    }

    public static String invalidMessage() {
        String s = RCServiceListDetail.P_InvalidMessage;
        return s;
    }

    public static String selected() {
        String s = RCServiceListDetail.P_Selected;
        return s;
    }

    public static String loaded() {
        String s = RCServiceListDetail.P_Loaded;
        return s;
    }
}
 
