// Generated by OABuilder
package test.xice.tsac.model.oa.propertypath;
 
import java.io.Serializable;

import test.xice.tsac.model.oa.*;
 
public class RCVerifyPPx implements PPxInterface, Serializable {
    private static final long serialVersionUID = 1L;
    public final String pp;  // propertyPath
     
    public RCVerifyPPx(String name) {
        this(null, name);
    }

    public RCVerifyPPx(PPxInterface parent, String name) {
        String s = null;
        if (parent != null) {
            s = parent.toString();
        }
        if (s == null) s = "";
        if (name != null && name.length() > 0) {
            if (s.length() > 0 && name.charAt(0) != ':') s += ".";
            s += name;
        }
        pp = s;
    }

    public RCDeployPPx rcDeploy() {
        RCDeployPPx ppx = new RCDeployPPx(this, RCVerify.P_RCDeploy);
        return ppx;
    }

    public RCExecutePPx rcExecute() {
        RCExecutePPx ppx = new RCExecutePPx(this, RCVerify.P_RCExecute);
        return ppx;
    }

    public RCVerifyDetailPPx rcVerifyDetails() {
        RCVerifyDetailPPx ppx = new RCVerifyDetailPPx(this, RCVerify.P_RCVerifyDetails);
        return ppx;
    }

    public String id() {
        return pp + "." + RCVerify.P_Id;
    }

    public String created() {
        return pp + "." + RCVerify.P_Created;
    }

    public String run() {
        return pp + ".run";
    }

    public String process() {
        return pp + ".process";
    }

    @Override
    public String toString() {
        return pp;
    }
}
 
