// Generated by OABuilder
package test.xice.tsac.model.oa.propertypath;
 
import test.xice.tsac.model.oa.*;
 
public class ServerPP {
    private static ApplicationPPx applications;
    private static OSVersionPPx osVersion;
    private static RCInstallDetailPPx rcInstallDetails;
    private static RCStageDetailPPx rcOrigStageDetails;
    private static RCServerListDetailPPx rcServerListDetails;
    private static RCStageDetailPPx rcStageDetails;
    private static SiloPPx silo;
     

    public static ApplicationPPx applications() {
        if (applications == null) applications = new ApplicationPPx(Server.P_Applications);
        return applications;
    }

    public static OSVersionPPx osVersion() {
        if (osVersion == null) osVersion = new OSVersionPPx(Server.P_OSVersion);
        return osVersion;
    }

    public static RCInstallDetailPPx rcInstallDetails() {
        if (rcInstallDetails == null) rcInstallDetails = new RCInstallDetailPPx(Server.P_RCInstallDetails);
        return rcInstallDetails;
    }

    public static RCStageDetailPPx rcOrigStageDetails() {
        if (rcOrigStageDetails == null) rcOrigStageDetails = new RCStageDetailPPx(Server.P_RCOrigStageDetails);
        return rcOrigStageDetails;
    }

    public static RCServerListDetailPPx rcServerListDetails() {
        if (rcServerListDetails == null) rcServerListDetails = new RCServerListDetailPPx(Server.P_RCServerListDetails);
        return rcServerListDetails;
    }

    public static RCStageDetailPPx rcStageDetails() {
        if (rcStageDetails == null) rcStageDetails = new RCStageDetailPPx(Server.P_RCStageDetails);
        return rcStageDetails;
    }

    public static SiloPPx silo() {
        if (silo == null) silo = new SiloPPx(Server.P_Silo);
        return silo;
    }

    public static String id() {
        String s = Server.P_Id;
        return s;
    }

    public static String created() {
        String s = Server.P_Created;
        return s;
    }

    public static String name() {
        String s = Server.P_Name;
        return s;
    }

    public static String hostName() {
        String s = Server.P_HostName;
        return s;
    }

    public static String ipAddress() {
        String s = Server.P_IpAddress;
        return s;
    }

    public static String dnsName() {
        String s = Server.P_DnsName;
        return s;
    }

    public static String shortDnsName() {
        String s = Server.P_ShortDnsName;
        return s;
    }

    public static String userId() {
        String s = Server.P_UserId;
        return s;
    }

    public static String displayName() {
        String s = Server.P_DisplayName;
        return s;
    }
}
 
