// Generated by OABuilder
package test.xice.tsac2.model.oa.propertypath;
 
import java.io.Serializable;

import test.xice.tsac2.model.oa.*;
 
public class AdminClientPPx implements PPxInterface, Serializable {
    private static final long serialVersionUID = 1L;
    public final String pp;  // propertyPath
     
    public AdminClientPPx(String name) {
        this(null, name);
    }

    public AdminClientPPx(PPxInterface parent, String name) {
        String s = null;
        if (parent != null) {
            s = parent.toString();
        }
        if (s == null) s = "";
        if (name != null && name.length() > 0) {
            if (s.length() > 0 && name.charAt(0) != ':') s += ".";
            s += name;
        }
        pp = s;
    }

    public AdminServerPPx adminServer() {
        AdminServerPPx ppx = new AdminServerPPx(this, AdminClient.P_AdminServer);
        return ppx;
    }

    public ApplicationPPx application() {
        ApplicationPPx ppx = new ApplicationPPx(this, AdminClient.P_Application);
        return ppx;
    }

    public String id() {
        return pp + "." + AdminClient.P_Id;
    }

    @Override
    public String toString() {
        return pp;
    }
}
 
