// Generated by OABuilder
package test.xice.tsac2.model.oa.propertypath;
 
import test.xice.tsac2.model.oa.*;
 
public class AdminClientPP {
    private static AdminServerPPx adminServer;
    private static ApplicationPPx application;
     

    public static AdminServerPPx adminServer() {
        if (adminServer == null) adminServer = new AdminServerPPx(AdminClient.P_AdminServer);
        return adminServer;
    }

    public static ApplicationPPx application() {
        if (application == null) application = new ApplicationPPx(AdminClient.P_Application);
        return application;
    }

    public static String id() {
        String s = AdminClient.P_Id;
        return s;
    }
}
 
