// Generated by OABuilder
package test.xice.tsac2.model.oa.propertypath;
 
import java.io.Serializable;

import test.xice.tsac2.model.oa.*;
 
public class LoginTypePPx implements PPxInterface, Serializable {
    private static final long serialVersionUID = 1L;
    public final String pp;  // propertyPath
     
    public LoginTypePPx(String name) {
        this(null, name);
    }

    public LoginTypePPx(PPxInterface parent, String name) {
        String s = null;
        if (parent != null) {
            s = parent.toString();
        }
        if (s == null) s = "";
        if (name != null && name.length() > 0) {
            if (s.length() > 0 && name.charAt(0) != ':') s += ".";
            s += name;
        }
        pp = s;
    }

    public UserLoginPPx userLogins() {
        UserLoginPPx ppx = new UserLoginPPx(this, LoginType.P_UserLogins);
        return ppx;
    }

    public String id() {
        return pp + "." + LoginType.P_Id;
    }

    public String name() {
        return pp + "." + LoginType.P_Name;
    }

    public String allowDuplicateLogin() {
        return pp + "." + LoginType.P_AllowDuplicateLogin;
    }

    public String seq() {
        return pp + "." + LoginType.P_Seq;
    }

    @Override
    public String toString() {
        return pp;
    }
}
 
