// Generated by OABuilder
package test.xice.tsac2.model.oa.propertypath;
 
import java.io.Serializable;

import test.xice.tsac2.model.oa.*;
 
public class RCInstalledVersionPPx implements PPxInterface, Serializable {
    private static final long serialVersionUID = 1L;
    public final String pp;  // propertyPath
     
    public RCInstalledVersionPPx(String name) {
        this(null, name);
    }

    public RCInstalledVersionPPx(PPxInterface parent, String name) {
        String s = null;
        if (parent != null) {
            s = parent.toString();
        }
        if (s == null) s = "";
        if (name != null && name.length() > 0) {
            if (s.length() > 0 && name.charAt(0) != ':') s += ".";
            s += name;
        }
        pp = s;
    }

    public EnvironmentPPx environment() {
        EnvironmentPPx ppx = new EnvironmentPPx(this, RCInstalledVersion.P_Environment);
        return ppx;
    }

    public RCExecutePPx rcExecute() {
        RCExecutePPx ppx = new RCExecutePPx(this, RCInstalledVersion.P_RCExecute);
        return ppx;
    }

    public RCInstalledVersionDetailPPx rcInstalledVersionDetails() {
        RCInstalledVersionDetailPPx ppx = new RCInstalledVersionDetailPPx(this, RCInstalledVersion.P_RCInstalledVersionDetails);
        return ppx;
    }

    public RemoteClientPPx remoteClient() {
        RemoteClientPPx ppx = new RemoteClientPPx(this, RCInstalledVersion.P_RemoteClient);
        return ppx;
    }

    public String id() {
        return pp + "." + RCInstalledVersion.P_Id;
    }

    public String created() {
        return pp + "." + RCInstalledVersion.P_Created;
    }

    public String canRun() {
        return pp + "." + RCInstalledVersion.P_CanRun;
    }

    public String canProcess() {
        return pp + "." + RCInstalledVersion.P_CanProcess;
    }

    public String canLoad() {
        return pp + "." + RCInstalledVersion.P_CanLoad;
    }

    public String run() {
        return pp + ".run";
    }

    public String process() {
        return pp + ".process";
    }

    public String load() {
        return pp + ".load";
    }

    @Override
    public String toString() {
        return pp;
    }
}
 
