// Generated by OABuilder
package test.xice.tsac3.model.oa.propertypath;
 
import java.io.Serializable;

import test.xice.tsac3.model.oa.*;
 
public class ServerStatusPPx implements PPxInterface, Serializable {
    private static final long serialVersionUID = 1L;
    public final String pp;  // propertyPath
    private GSMRClientPPx gsmrClients;
    private ServerPPx servers;
     
    public ServerStatusPPx(String name) {
        this(null, name);
    }

    public ServerStatusPPx(PPxInterface parent, String name) {
        String s = null;
        if (parent != null) {
            s = parent.toString();
        }
        if (s == null) s = "";
        if (name != null) {
            if (s.length() > 0) s += ".";
            s += name;
        }
        pp = s;
    }

    public GSMRClientPPx gsmrClients() {
        if (gsmrClients == null) gsmrClients = new GSMRClientPPx(this, ServerStatus.P_GSMRClients);
        return gsmrClients;
    }

    public ServerPPx servers() {
        if (servers == null) servers = new ServerPPx(this, ServerStatus.P_Servers);
        return servers;
    }

    public String id() {
        return pp + "." + ServerStatus.P_Id;
    }

    public String created() {
        return pp + "." + ServerStatus.P_Created;
    }

    public String name() {
        return pp + "." + ServerStatus.P_Name;
    }

    public String type() {
        return pp + "." + ServerStatus.P_Type;
    }

    public String color() {
        return pp + "." + ServerStatus.P_Color;
    }

    @Override
    public String toString() {
        return pp;
    }
}
 
