// Generated by OABuilder
package test.xice.tsam.model.oa.search;

import java.util.logging.*;

import test.xice.tsam.model.oa.SiloConfig;
import test.xice.tsam.model.oa.search.SiloConfigSearch;
import com.viaoa.annotation.*;
import com.viaoa.datasource.*;
import com.viaoa.object.*;
import com.viaoa.hub.*;
import com.viaoa.util.*;
import com.viaoa.filter.OAQueryFilter;

import test.xice.tsam.model.oa.*;
import test.xice.tsam.model.oa.propertypath.*;

@OAClass(useDataSource=false, localOnly=true)
public class SiloConfigSearch extends OAObject {
    private static final long serialVersionUID = 1L;
    private static Logger LOG = Logger.getLogger(SiloConfigSearch.class.getName());


    public void reset() {
    }

    public boolean isDataEntered() {
        return false;
    }

    protected String extraWhere;
    protected Object[] extraWhereParams;
    protected OAFilter<SiloConfig> filterExtraWhere;

    public void setExtraWhere(String s, Object ... args) {
        this.extraWhere = s;
        this.extraWhereParams = args;
        if (!OAString.isEmpty(s) && getExtraWhereFilter() == null) {
            OAFilter<SiloConfig> f = new OAQueryFilter<SiloConfig>(SiloConfig.class, s, args);
            setExtraWhereFilter(f);
        }
    }
    public void setExtraWhereFilter(OAFilter<SiloConfig> filter) {
        this.filterExtraWhere = filter;
    }
    public OAFilter<SiloConfig> getExtraWhereFilter() {
        return this.filterExtraWhere;
    }

    public OASelect<SiloConfig> getSelect() {
        String sql = "";
        String sortOrder = "";
        Object[] args = new Object[0];

        if (!OAString.isEmpty(extraWhere)) {
            if (sql.length() > 0) sql = "(" + sql + ") AND ";
            sql += extraWhere;
            args = OAArray.add(Object.class, args, extraWhereParams);
        }

        OASelect<SiloConfig> sel = new OASelect<SiloConfig>(SiloConfig.class, sql, args, sortOrder);
        sel.setDataSourceFilter(this.getDataSourceFilter());
        sel.setFilter(this.getCustomFilter());
        return sel;
    }

    private OAFilter<SiloConfig> filterDataSourceFilter;
    public OAFilter<SiloConfig> getDataSourceFilter() {
        if (filterDataSourceFilter != null) return filterDataSourceFilter;
        filterDataSourceFilter = new OAFilter<SiloConfig>() {
            @Override
            public boolean isUsed(SiloConfig siloConfig) {
                return SiloConfigSearch.this.isUsedForDataSourceFilter(siloConfig);
            }
        };
        return filterDataSourceFilter;
    }
    
    private OAFilter<SiloConfig> filterCustomFilter;
    public OAFilter<SiloConfig> getCustomFilter() {
        if (filterCustomFilter != null) return filterCustomFilter;
        filterCustomFilter = new OAFilter<SiloConfig>() {
            @Override
            public boolean isUsed(SiloConfig siloConfig) {
                boolean b = SiloConfigSearch.this.isUsedForCustomFilter(siloConfig);
                if (b && filterExtraWhere != null) b = filterExtraWhere.isUsed(siloConfig);
                return b;
            }
        };
        return filterCustomFilter;
    }
    
    public boolean isUsedForDataSourceFilter(SiloConfig siloConfig) {
        return true;
    }
    public boolean isUsedForCustomFilter(SiloConfig siloConfig) {
        return true;
    }
}
