// Generated by OABuilder
package test.xice.tsac3.model.oa.propertypath;
 
import java.io.Serializable;

import test.xice.tsac3.model.oa.*;
 
public class ClientAppTypePPx implements PPxInterface, Serializable {
    private static final long serialVersionUID = 1L;
    public final String pp;  // propertyPath
    private UserLoginHistoryPPx userLoginHistories;
    private UserLoginPPx userLogins;
     
    public ClientAppTypePPx(String name) {
        this(null, name);
    }

    public ClientAppTypePPx(PPxInterface parent, String name) {
        String s = null;
        if (parent != null) {
            s = parent.toString();
        }
        if (s == null) s = "";
        if (name != null) {
            if (s.length() > 0) s += ".";
            s += name;
        }
        pp = s;
    }

    public UserLoginHistoryPPx userLoginHistories() {
        if (userLoginHistories == null) userLoginHistories = new UserLoginHistoryPPx(this, ClientAppType.P_UserLoginHistories);
        return userLoginHistories;
    }

    public UserLoginPPx userLogins() {
        if (userLogins == null) userLogins = new UserLoginPPx(this, ClientAppType.P_UserLogins);
        return userLogins;
    }

    public String id() {
        return pp + "." + ClientAppType.P_Id;
    }

    public String name() {
        return pp + "." + ClientAppType.P_Name;
    }

    public String seq() {
        return pp + "." + ClientAppType.P_Seq;
    }

    @Override
    public String toString() {
        return pp;
    }
}
 
