// Generated by OABuilder
package test.xice.tsac3.model.oa.propertypath;
 
import test.xice.tsac3.model.oa.*;
 
public class SiloPP {
    private static EnvironmentPPx environment;
    private static GSMRServerPPx gsmrServers;
    private static LLADServerPPx lladServer;
    private static MRADServerPPx mradServer;
    private static ServerGroupPPx serverGroups;
    private static ServerPPx servers;
    private static SiloServerInfoPPx siloServerInfos;
    private static SiloTypePPx siloType;
     

    public static EnvironmentPPx environment() {
        if (environment == null) environment = new EnvironmentPPx(Silo.P_Environment);
        return environment;
    }

    public static GSMRServerPPx gsmrServers() {
        if (gsmrServers == null) gsmrServers = new GSMRServerPPx(Silo.P_GSMRServers);
        return gsmrServers;
    }

    public static LLADServerPPx lladServer() {
        if (lladServer == null) lladServer = new LLADServerPPx(Silo.P_LLADServer);
        return lladServer;
    }

    public static MRADServerPPx mradServer() {
        if (mradServer == null) mradServer = new MRADServerPPx(Silo.P_MRADServer);
        return mradServer;
    }

    public static ServerGroupPPx serverGroups() {
        if (serverGroups == null) serverGroups = new ServerGroupPPx(Silo.P_ServerGroups);
        return serverGroups;
    }

    public static ServerPPx servers() {
        if (servers == null) servers = new ServerPPx(Silo.P_Servers);
        return servers;
    }

    public static SiloServerInfoPPx siloServerInfos() {
        if (siloServerInfos == null) siloServerInfos = new SiloServerInfoPPx(Silo.P_SiloServerInfos);
        return siloServerInfos;
    }

    public static SiloTypePPx siloType() {
        if (siloType == null) siloType = new SiloTypePPx(Silo.P_SiloType);
        return siloType;
    }

    public static String id() {
        String s = Silo.P_Id;
        return s;
    }

    public static String networkMask() {
        String s = Silo.P_NetworkMask;
        return s;
    }
}
 
