// Generated by OABuilder
package test.xice.tsac2.model.oa.propertypath;
 
import java.io.Serializable;

import test.xice.tsac2.model.oa.*;
 
public class LLADServerPPx implements PPxInterface, Serializable {
    private static final long serialVersionUID = 1L;
    public final String pp;  // propertyPath
     
    public LLADServerPPx(String name) {
        this(null, name);
    }

    public LLADServerPPx(PPxInterface parent, String name) {
        String s = null;
        if (parent != null) {
            s = parent.toString();
        }
        if (s == null) s = "";
        if (name != null && name.length() > 0) {
            if (s.length() > 0 && name.charAt(0) != ':') s += ".";
            s += name;
        }
        pp = s;
    }

    public ApplicationPPx application() {
        ApplicationPPx ppx = new ApplicationPPx(this, LLADServer.P_Application);
        return ppx;
    }

    public LLADClientPPx lladClients() {
        LLADClientPPx ppx = new LLADClientPPx(this, LLADServer.P_LLADClients);
        return ppx;
    }

    public RemoteMessagePPx remoteMessages() {
        RemoteMessagePPx ppx = new RemoteMessagePPx(this, LLADServer.P_RemoteMessages);
        return ppx;
    }

    public SiloPPx silo() {
        SiloPPx ppx = new SiloPPx(this, LLADServer.P_Silo);
        return ppx;
    }

    public UserPPx users() {
        UserPPx ppx = new UserPPx(this, LLADServer.P_Users);
        return ppx;
    }

    public String id() {
        return pp + "." + LLADServer.P_Id;
    }

    public String remoteStarted() {
        return pp + "." + LLADServer.P_RemoteStarted;
    }

    public String connected() {
        return pp + "." + LLADServer.P_Connected;
    }

    public String enableLLADCommands() {
        return pp + "." + LLADServer.P_EnableLLADCommands;
    }

    public String refreshUserCache() {
        return pp + ".refreshUserCache";
    }

    public String reloadAllUsers() {
        return pp + ".reloadAllUsers";
    }

    public String connect() {
        return pp + ".connect";
    }

    public String disconnect() {
        return pp + ".disconnect";
    }

    @Override
    public String toString() {
        return pp;
    }
}
 
