// Generated by OABuilder
package test.hifive.model.oa.propertypath;
 
import test.hifive.model.oa.*;
 
public class AddressTypePP {
    private static AddressPPx addresses;
     

    public static AddressPPx addresses() {
        if (addresses == null) addresses = new AddressPPx(AddressType.P_Addresses);
        return addresses;
    }

    public static String id() {
        String s = AddressType.P_Id;
        return s;
    }

    public static String name() {
        String s = AddressType.P_Name;
        return s;
    }

    public static String type() {
        String s = AddressType.P_Type;
        return s;
    }
}
 
