// Generated by OABuilder
package test.hifive.model.oa.propertypath;
 
import test.hifive.model.oa.*;
 
public class CatalogPP {
    private static SectionPPx sections;
     

    public static SectionPPx sections() {
        if (sections == null) sections = new SectionPPx(Catalog.P_Sections);
        return sections;
    }

    public static String id() {
        String s = Catalog.P_Id;
        return s;
    }

    public static String created() {
        String s = Catalog.P_Created;
        return s;
    }

    public static String name() {
        String s = Catalog.P_Name;
        return s;
    }
}
 
