// Generated by OABuilder
package test.hifive.model.oa.propertypath;
 
import test.hifive.model.oa.*;
 
public class CompanyPP {
    private static LocationTypePPx locationTypes;
    private static ProgramPPx programs;
     

    public static LocationTypePPx locationTypes() {
        if (locationTypes == null) locationTypes = new LocationTypePPx(Company.P_LocationTypes);
        return locationTypes;
    }

    public static ProgramPPx programs() {
        if (programs == null) programs = new ProgramPPx(Company.P_Programs);
        return programs;
    }

    public static String id() {
        String s = Company.P_Id;
        return s;
    }

    public static String created() {
        String s = Company.P_Created;
        return s;
    }

    public static String name() {
        String s = Company.P_Name;
        return s;
    }
}
 
