// Generated by OABuilder
package test.hifive.model.oa.propertypath;
 
import test.hifive.model.oa.*;
 
public class EmployeeEcardToPP {
    private static EmailPPx email;
    private static EmployeeEcardPPx employeeEcard;
    private static EmployeePPx toEmployee;
     

    public static EmailPPx email() {
        if (email == null) email = new EmailPPx(EmployeeEcardTo.P_Email);
        return email;
    }

    public static EmployeeEcardPPx employeeEcard() {
        if (employeeEcard == null) employeeEcard = new EmployeeEcardPPx(EmployeeEcardTo.P_EmployeeEcard);
        return employeeEcard;
    }

    public static EmployeePPx toEmployee() {
        if (toEmployee == null) toEmployee = new EmployeePPx(EmployeeEcardTo.P_ToEmployee);
        return toEmployee;
    }

    public static String id() {
        String s = EmployeeEcardTo.P_Id;
        return s;
    }

    public static String emailAddress() {
        String s = EmployeeEcardTo.P_EmailAddress;
        return s;
    }

    public static String name() {
        String s = EmployeeEcardTo.P_Name;
        return s;
    }

    public static String includeManager() {
        String s = EmployeeEcardTo.P_IncludeManager;
        return s;
    }

    public static String pdfBytes() {
        String s = EmployeeEcardTo.P_PdfBytes;
        return s;
    }

    public static String viewPdf() {
        String s = "viewPdf";
        return s;
    }
}
 
