// Generated by OABuilder
package test.hifive.model.oa.propertypath;
 
import java.io.Serializable;

import test.hifive.model.oa.*;
 
public class InspirePPx implements PPxInterface, Serializable {
    private static final long serialVersionUID = 1L;
    public final String pp;  // propertyPath
    private EmailPPx email;
    private EmployeePPx employee;
    private InspireAwardLevelPPx inspireAwardLevel;
    private InspireCoreValuePPx inspireCoreValue;
    private InspireRecipientPPx inspireRecipients;
     
    public InspirePPx(String name) {
        this(null, name);
    }

    public InspirePPx(PPxInterface parent, String name) {
        String s = null;
        if (parent != null) {
            s = parent.toString();
        }
        if (s == null) s = "";
        if (name != null) {
            if (s.length() > 0) s += ".";
            s += name;
        }
        pp = s;
    }

    public EmailPPx email() {
        if (email == null) email = new EmailPPx(this, Inspire.P_Email);
        return email;
    }

    public EmployeePPx employee() {
        if (employee == null) employee = new EmployeePPx(this, Inspire.P_Employee);
        return employee;
    }

    public InspireAwardLevelPPx inspireAwardLevel() {
        if (inspireAwardLevel == null) inspireAwardLevel = new InspireAwardLevelPPx(this, Inspire.P_InspireAwardLevel);
        return inspireAwardLevel;
    }

    public InspireCoreValuePPx inspireCoreValue() {
        if (inspireCoreValue == null) inspireCoreValue = new InspireCoreValuePPx(this, Inspire.P_InspireCoreValue);
        return inspireCoreValue;
    }

    public InspireRecipientPPx inspireRecipients() {
        if (inspireRecipients == null) inspireRecipients = new InspireRecipientPPx(this, Inspire.P_InspireRecipients);
        return inspireRecipients;
    }

    public String id() {
        return pp + "." + Inspire.P_Id;
    }

    public String created() {
        return pp + "." + Inspire.P_Created;
    }

    public String reason() {
        return pp + "." + Inspire.P_Reason;
    }

    public String message() {
        return pp + "." + Inspire.P_Message;
    }

    public String wasAddedToEmployee() {
        return pp + "." + Inspire.P_WasAddedToEmployee;
    }

    public String recipientNames() {
        return pp + "." + Inspire.P_RecipientNames;
    }

    public String updateEmail() {
        return pp + ".updateEmail";
    }

    @Override
    public String toString() {
        return pp;
    }
}
 
