// Generated by OABuilder
package test.hifive.model.oa.propertypath;
 
import java.io.Serializable;

import test.hifive.model.oa.*;
 
public class LocationPageGroupPPx implements PPxInterface, Serializable {
    private static final long serialVersionUID = 1L;
    public final String pp;  // propertyPath
    private LocationPPx location;
    private PageGroupPPx pageGroup;
     
    public LocationPageGroupPPx(String name) {
        this(null, name);
    }

    public LocationPageGroupPPx(PPxInterface parent, String name) {
        String s = null;
        if (parent != null) {
            s = parent.toString();
        }
        if (s == null) s = "";
        if (name != null) {
            if (s.length() > 0) s += ".";
            s += name;
        }
        pp = s;
    }

    public LocationPPx location() {
        if (location == null) location = new LocationPPx(this, LocationPageGroup.P_Location);
        return location;
    }

    public PageGroupPPx pageGroup() {
        if (pageGroup == null) pageGroup = new PageGroupPPx(this, LocationPageGroup.P_PageGroup);
        return pageGroup;
    }

    public String id() {
        return pp + "." + LocationPageGroup.P_Id;
    }

    public String created() {
        return pp + "." + LocationPageGroup.P_Created;
    }

    public String seq() {
        return pp + "." + LocationPageGroup.P_Seq;
    }

    @Override
    public String toString() {
        return pp;
    }
}
 
