// Generated by OABuilder
package test.hifive.model.oa.propertypath;
 
import test.hifive.model.oa.*;
 
public class PageGroupPP {
    private static LocationPageGroupPPx locationPageGroups;
    private static PageGroupPageInfoPPx pageGroupPageInfos;
    private static PageGroupPPx pageGroups;
    private static PageGroupPPx parentPageGroup;
    private static ProgramPageGroupPPx programPageGroups;
     

    public static LocationPageGroupPPx locationPageGroups() {
        if (locationPageGroups == null) locationPageGroups = new LocationPageGroupPPx(PageGroup.P_LocationPageGroups);
        return locationPageGroups;
    }

    public static PageGroupPageInfoPPx pageGroupPageInfos() {
        if (pageGroupPageInfos == null) pageGroupPageInfos = new PageGroupPageInfoPPx(PageGroup.P_PageGroupPageInfos);
        return pageGroupPageInfos;
    }

    public static PageGroupPPx pageGroups() {
        if (pageGroups == null) pageGroups = new PageGroupPPx(PageGroup.P_PageGroups);
        return pageGroups;
    }

    public static PageGroupPPx parentPageGroup() {
        if (parentPageGroup == null) parentPageGroup = new PageGroupPPx(PageGroup.P_ParentPageGroup);
        return parentPageGroup;
    }

    public static ProgramPageGroupPPx programPageGroups() {
        if (programPageGroups == null) programPageGroups = new ProgramPageGroupPPx(PageGroup.P_ProgramPageGroups);
        return programPageGroups;
    }

    public static String id() {
        String s = PageGroup.P_Id;
        return s;
    }

    public static String created() {
        String s = PageGroup.P_Created;
        return s;
    }

    public static String seq() {
        String s = PageGroup.P_Seq;
        return s;
    }

    public static String name() {
        String s = PageGroup.P_Name;
        return s;
    }
}
 
