// Generated by OABuilder
package test.hifive.model.oa.propertypath;
 
import test.hifive.model.oa.*;
 
public class PointsCoreValuePP {
    private static LocationPPx location;
    private static PointsRecordPPx pointsRecords;
    private static ProgramPPx program;
     

    public static LocationPPx location() {
        if (location == null) location = new LocationPPx(PointsCoreValue.P_Location);
        return location;
    }

    public static PointsRecordPPx pointsRecords() {
        if (pointsRecords == null) pointsRecords = new PointsRecordPPx(PointsCoreValue.P_PointsRecords);
        return pointsRecords;
    }

    public static ProgramPPx program() {
        if (program == null) program = new ProgramPPx(PointsCoreValue.P_Program);
        return program;
    }

    public static String id() {
        String s = PointsCoreValue.P_Id;
        return s;
    }

    public static String name() {
        String s = PointsCoreValue.P_Name;
        return s;
    }

    public static String seq() {
        String s = PointsCoreValue.P_Seq;
        return s;
    }

    public static String description() {
        String s = PointsCoreValue.P_Description;
        return s;
    }
}
 
