// Generated by OABuilder
package test.hifive.model.oa.propertypath;
 
import test.hifive.model.oa.*;
 
public class QuestionPP {
    private static AnswerPPx answers;
    private static QuestionResultPPx questionResults;
    private static QuizPPx quiz;
     

    public static AnswerPPx answers() {
        if (answers == null) answers = new AnswerPPx(Question.P_Answers);
        return answers;
    }

    public static QuestionResultPPx questionResults() {
        if (questionResults == null) questionResults = new QuestionResultPPx(Question.P_QuestionResults);
        return questionResults;
    }

    public static QuizPPx quiz() {
        if (quiz == null) quiz = new QuizPPx(Question.P_Quiz);
        return quiz;
    }

    public static String id() {
        String s = Question.P_Id;
        return s;
    }

    public static String questionText() {
        String s = Question.P_QuestionText;
        return s;
    }
}
 
