// Generated by OABuilder
package test.hifive.model.oa.propertypath;
 
import java.io.Serializable;

import test.hifive.model.oa.*;
 
public class ShipToPPx implements PPxInterface, Serializable {
    private static final long serialVersionUID = 1L;
    public final String pp;  // propertyPath
    private AddressPPx address;
    private EmployeeAwardPPx employeeAward;
    private InspireOrderPPx inspireOrder;
     
    public ShipToPPx(String name) {
        this(null, name);
    }

    public ShipToPPx(PPxInterface parent, String name) {
        String s = null;
        if (parent != null) {
            s = parent.toString();
        }
        if (s == null) s = "";
        if (name != null) {
            if (s.length() > 0) s += ".";
            s += name;
        }
        pp = s;
    }

    public AddressPPx address() {
        if (address == null) address = new AddressPPx(this, ShipTo.P_Address);
        return address;
    }

    public EmployeeAwardPPx employeeAward() {
        if (employeeAward == null) employeeAward = new EmployeeAwardPPx(this, ShipTo.P_EmployeeAward);
        return employeeAward;
    }

    public InspireOrderPPx inspireOrder() {
        if (inspireOrder == null) inspireOrder = new InspireOrderPPx(this, ShipTo.P_InspireOrder);
        return inspireOrder;
    }

    public String id() {
        return pp + "." + ShipTo.P_Id;
    }

    public String created() {
        return pp + "." + ShipTo.P_Created;
    }

    public String name() {
        return pp + "." + ShipTo.P_Name;
    }

    public String note() {
        return pp + "." + ShipTo.P_Note;
    }

    public String email() {
        return pp + "." + ShipTo.P_Email;
    }

    public String phoneNumber() {
        return pp + "." + ShipTo.P_PhoneNumber;
    }

    @Override
    public String toString() {
        return pp;
    }
}
 
