// Generated by OABuilder
package test.hifive.model.oa.propertypath;
 
import test.hifive.model.oa.*;
 
public class AddOnItemPP {
    private static AwardTypePPx awardType;
    private static EmployeeAwardPPx employeeAwards;
    private static ItemPPx item;
    private static LocationPPx location;
    private static ProgramPPx program;
     

    public static AwardTypePPx awardType() {
        if (awardType == null) awardType = new AwardTypePPx(AddOnItem.P_AwardType);
        return awardType;
    }

    public static EmployeeAwardPPx employeeAwards() {
        if (employeeAwards == null) employeeAwards = new EmployeeAwardPPx(AddOnItem.P_EmployeeAwards);
        return employeeAwards;
    }

    public static ItemPPx item() {
        if (item == null) item = new ItemPPx(AddOnItem.P_Item);
        return item;
    }

    public static LocationPPx location() {
        if (location == null) location = new LocationPPx(AddOnItem.P_Location);
        return location;
    }

    public static ProgramPPx program() {
        if (program == null) program = new ProgramPPx(AddOnItem.P_Program);
        return program;
    }

    public static String id() {
        String s = AddOnItem.P_Id;
        return s;
    }

    public static String created() {
        String s = AddOnItem.P_Created;
        return s;
    }

    public static String value() {
        String s = AddOnItem.P_Value;
        return s;
    }
}
 
