// Generated by OABuilder
package test.hifive.model.oa.propertypath;
 
import java.io.Serializable;

import test.hifive.model.oa.*;
 
public class EmailTypePPx implements PPxInterface, Serializable {
    private static final long serialVersionUID = 1L;
    public final String pp;  // propertyPath
    private LocationEmailTypePPx locationEmailTypes;
    private ProgramEmailTypePPx programEmailTypes;
     
    public EmailTypePPx(String name) {
        this(null, name);
    }

    public EmailTypePPx(PPxInterface parent, String name) {
        String s = null;
        if (parent != null) {
            s = parent.toString();
        }
        if (s == null) s = "";
        if (name != null) {
            if (s.length() > 0) s += ".";
            s += name;
        }
        pp = s;
    }

    public LocationEmailTypePPx locationEmailTypes() {
        if (locationEmailTypes == null) locationEmailTypes = new LocationEmailTypePPx(this, EmailType.P_LocationEmailTypes);
        return locationEmailTypes;
    }

    public ProgramEmailTypePPx programEmailTypes() {
        if (programEmailTypes == null) programEmailTypes = new ProgramEmailTypePPx(this, EmailType.P_ProgramEmailTypes);
        return programEmailTypes;
    }

    public String id() {
        return pp + "." + EmailType.P_Id;
    }

    public String created() {
        return pp + "." + EmailType.P_Created;
    }

    public String seq() {
        return pp + "." + EmailType.P_Seq;
    }

    public String name() {
        return pp + "." + EmailType.P_Name;
    }

    public String type() {
        return pp + "." + EmailType.P_Type;
    }

    public String subject() {
        return pp + "." + EmailType.P_Subject;
    }

    public String text() {
        return pp + "." + EmailType.P_Text;
    }

    public String note() {
        return pp + "." + EmailType.P_Note;
    }

    public String textFieldClass() {
        return pp + ".textFieldClass";
    }

    @Override
    public String toString() {
        return pp;
    }
}
 
