// Generated by OABuilder
package test.hifive.model.oa.propertypath;
 
import java.io.Serializable;

import test.hifive.model.oa.*;
 
public class InspireCoreValuePPx implements PPxInterface, Serializable {
    private static final long serialVersionUID = 1L;
    public final String pp;  // propertyPath
    private EmployeePPx employee;
    private InspirePPx inspires;
    private LocationPPx location;
    private ProgramPPx program;
     
    public InspireCoreValuePPx(String name) {
        this(null, name);
    }

    public InspireCoreValuePPx(PPxInterface parent, String name) {
        String s = null;
        if (parent != null) {
            s = parent.toString();
        }
        if (s == null) s = "";
        if (name != null) {
            if (s.length() > 0) s += ".";
            s += name;
        }
        pp = s;
    }

    public EmployeePPx employee() {
        if (employee == null) employee = new EmployeePPx(this, InspireCoreValue.P_Employee);
        return employee;
    }

    public InspirePPx inspires() {
        if (inspires == null) inspires = new InspirePPx(this, InspireCoreValue.P_Inspires);
        return inspires;
    }

    public LocationPPx location() {
        if (location == null) location = new LocationPPx(this, InspireCoreValue.P_Location);
        return location;
    }

    public ProgramPPx program() {
        if (program == null) program = new ProgramPPx(this, InspireCoreValue.P_Program);
        return program;
    }

    public String id() {
        return pp + "." + InspireCoreValue.P_Id;
    }

    public String name() {
        return pp + "." + InspireCoreValue.P_Name;
    }

    public String seq() {
        return pp + "." + InspireCoreValue.P_Seq;
    }

    @Override
    public String toString() {
        return pp;
    }
}
 
