// Generated by OABuilder
package test.hifive.model.oa.propertypath;
 
import java.io.Serializable;

import test.hifive.model.oa.*;
 
public class PointsIssuancePPx implements PPxInterface, Serializable {
    private static final long serialVersionUID = 1L;
    public final String pp;  // propertyPath
    private EmployeePPx fromEmployee;
    private EmployeePPx toEmployee;
     
    public PointsIssuancePPx(String name) {
        this(null, name);
    }

    public PointsIssuancePPx(PPxInterface parent, String name) {
        String s = null;
        if (parent != null) {
            s = parent.toString();
        }
        if (s == null) s = "";
        if (name != null) {
            if (s.length() > 0) s += ".";
            s += name;
        }
        pp = s;
    }

    public EmployeePPx fromEmployee() {
        if (fromEmployee == null) fromEmployee = new EmployeePPx(this, PointsIssuance.P_FromEmployee);
        return fromEmployee;
    }

    public EmployeePPx toEmployee() {
        if (toEmployee == null) toEmployee = new EmployeePPx(this, PointsIssuance.P_ToEmployee);
        return toEmployee;
    }

    public String id() {
        return pp + "." + PointsIssuance.P_Id;
    }

    public String created() {
        return pp + "." + PointsIssuance.P_Created;
    }

    public String points() {
        return pp + "." + PointsIssuance.P_Points;
    }

    public String description() {
        return pp + "." + PointsIssuance.P_Description;
    }

    @Override
    public String toString() {
        return pp;
    }
}
 
