// Generated by OABuilder
package test.hifive.model.oa.propertypath;
 
import java.io.Serializable;

import test.hifive.model.oa.*;
 
public class PointsCoreValuePPx implements PPxInterface, Serializable {
    private static final long serialVersionUID = 1L;
    public final String pp;  // propertyPath
    private LocationPPx location;
    private PointsRecordPPx pointsRecords;
    private ProgramPPx program;
     
    public PointsCoreValuePPx(String name) {
        this(null, name);
    }

    public PointsCoreValuePPx(PPxInterface parent, String name) {
        String s = null;
        if (parent != null) {
            s = parent.toString();
        }
        if (s == null) s = "";
        if (name != null) {
            if (s.length() > 0) s += ".";
            s += name;
        }
        pp = s;
    }

    public LocationPPx location() {
        if (location == null) location = new LocationPPx(this, PointsCoreValue.P_Location);
        return location;
    }

    public PointsRecordPPx pointsRecords() {
        if (pointsRecords == null) pointsRecords = new PointsRecordPPx(this, PointsCoreValue.P_PointsRecords);
        return pointsRecords;
    }

    public ProgramPPx program() {
        if (program == null) program = new ProgramPPx(this, PointsCoreValue.P_Program);
        return program;
    }

    public String id() {
        return pp + "." + PointsCoreValue.P_Id;
    }

    public String name() {
        return pp + "." + PointsCoreValue.P_Name;
    }

    public String seq() {
        return pp + "." + PointsCoreValue.P_Seq;
    }

    public String description() {
        return pp + "." + PointsCoreValue.P_Description;
    }

    @Override
    public String toString() {
        return pp;
    }
}
 
