// Generated by OABuilder
package test.hifive.model.oa.propertypath;
 
import test.hifive.model.oa.*;
 
public class ProgramPageGroupPP {
    private static PageGroupPPx pageGroup;
    private static ProgramPPx program;
     

    public static PageGroupPPx pageGroup() {
        if (pageGroup == null) pageGroup = new PageGroupPPx(ProgramPageGroup.P_PageGroup);
        return pageGroup;
    }

    public static ProgramPPx program() {
        if (program == null) program = new ProgramPPx(ProgramPageGroup.P_Program);
        return program;
    }

    public static String id() {
        String s = ProgramPageGroup.P_Id;
        return s;
    }

    public static String created() {
        String s = ProgramPageGroup.P_Created;
        return s;
    }

    public static String seq() {
        String s = ProgramPageGroup.P_Seq;
        return s;
    }
}
 
