// Generated by OABuilder
package test.hifive.model.oa.propertypath;
 
import java.io.Serializable;

import test.hifive.model.oa.*;
 
public class QuestionPPx implements PPxInterface, Serializable {
    private static final long serialVersionUID = 1L;
    public final String pp;  // propertyPath
    private AnswerPPx answers;
    private QuestionResultPPx questionResults;
    private QuizPPx quiz;
     
    public QuestionPPx(String name) {
        this(null, name);
    }

    public QuestionPPx(PPxInterface parent, String name) {
        String s = null;
        if (parent != null) {
            s = parent.toString();
        }
        if (s == null) s = "";
        if (name != null) {
            if (s.length() > 0) s += ".";
            s += name;
        }
        pp = s;
    }

    public AnswerPPx answers() {
        if (answers == null) answers = new AnswerPPx(this, Question.P_Answers);
        return answers;
    }

    public QuestionResultPPx questionResults() {
        if (questionResults == null) questionResults = new QuestionResultPPx(this, Question.P_QuestionResults);
        return questionResults;
    }

    public QuizPPx quiz() {
        if (quiz == null) quiz = new QuizPPx(this, Question.P_Quiz);
        return quiz;
    }

    public String id() {
        return pp + "." + Question.P_Id;
    }

    public String questionText() {
        return pp + "." + Question.P_QuestionText;
    }

    @Override
    public String toString() {
        return pp;
    }
}
 
