// Generated by OABuilder
package test.hifive.model.oa.propertypath;
 
import java.io.Serializable;

import test.hifive.model.oa.*;
 
public class ValuePPx implements PPxInterface, Serializable {
    private static final long serialVersionUID = 1L;
    public final String pp;  // propertyPath
    private CardPPx cards;
    private EmployeeAwardPPx employeeAward;
    private AwardCardOrderPPx inspireAwardCardOrder;
     
    public ValuePPx(String name) {
        this(null, name);
    }

    public ValuePPx(PPxInterface parent, String name) {
        String s = null;
        if (parent != null) {
            s = parent.toString();
        }
        if (s == null) s = "";
        if (name != null) {
            if (s.length() > 0) s += ".";
            s += name;
        }
        pp = s;
    }

    public CardPPx cards() {
        if (cards == null) cards = new CardPPx(this, Value.P_Cards);
        return cards;
    }

    public EmployeeAwardPPx employeeAward() {
        if (employeeAward == null) employeeAward = new EmployeeAwardPPx(this, Value.P_EmployeeAward);
        return employeeAward;
    }

    public AwardCardOrderPPx inspireAwardCardOrder() {
        if (inspireAwardCardOrder == null) inspireAwardCardOrder = new AwardCardOrderPPx(this, Value.P_InspireAwardCardOrder);
        return inspireAwardCardOrder;
    }

    public String id() {
        return pp + "." + Value.P_Id;
    }

    public String value() {
        return pp + "." + Value.P_Value;
    }

    public String name() {
        return pp + "." + Value.P_Name;
    }

    @Override
    public String toString() {
        return pp;
    }
}
 
