// Generated by OABuilder
package test.xice.tsac3.model.oa.search;

import com.viaoa.annotation.*;
import com.viaoa.object.*;
import com.viaoa.hub.*;
import com.viaoa.util.*;
import com.viaoa.util.filter.OAQueryFilter;

import test.xice.tsac3.model.oa.*;

import com.viaoa.ds.*;

@OAClass(useDataSource=false, localOnly=true)
public class MarketTypeSearch extends OAObject {
    private static final long serialVersionUID = 1L;



    public void reset() {
    }

    public boolean isDataEntered() {
        return false;
    }

    protected String extraWhere;
    protected Object[] extraWhereParams;
    protected OAFilter<MarketType> filterExtraWhere;

    public void setExtraWhere(String s, Object ... args) {
        this.extraWhere = s;
        this.extraWhereParams = args;
        if (!OAString.isEmpty(s) && getExtraWhereFilter() == null) {
            OAFilter<MarketType> f = new OAQueryFilter<MarketType>(MarketType.class, s, args);
            setExtraWhereFilter(f);
        }
    }
    public void setExtraWhereFilter(OAFilter<MarketType> filter) {
        this.filterExtraWhere = filter;
    }
    public OAFilter<MarketType> getExtraWhereFilter() {
        return this.filterExtraWhere;
    }

    public OASelect<MarketType> getSelect() {
        String sql = "";
        String sortOrder = MarketType.P_Seq;
        Object[] args = new Object[0];

        if (!OAString.isEmpty(extraWhere)) {
            if (sql.length() > 0) sql = "(" + sql + ") AND ";
            sql += extraWhere;
            args = OAArray.add(Object.class, args, extraWhereParams);
        }

        OASelect<MarketType> sel = new OASelect<MarketType>(MarketType.class, sql, args, sortOrder);
        sel.setDataSourceFilter(this.getDataSourceFilter());
        sel.setFilter(this.getCustomFilter());
        return sel;
    }

    private OAFilter<MarketType> filterDataSourceFilter;
    public OAFilter<MarketType> getDataSourceFilter() {
        if (filterDataSourceFilter != null) return filterDataSourceFilter;
        filterDataSourceFilter = new OAFilter<MarketType>() {
            @Override
            public boolean isUsed(MarketType marketType) {
                return MarketTypeSearch.this.isUsedForDataSourceFilter(marketType);
            }
        };
        return filterDataSourceFilter;
    }
    
    private OAFilter<MarketType> filterCustomFilter;
    public OAFilter<MarketType> getCustomFilter() {
        if (filterCustomFilter != null) return filterCustomFilter;
        filterCustomFilter = new OAFilter<MarketType>() {
            @Override
            public boolean isUsed(MarketType marketType) {
                boolean b = MarketTypeSearch.this.isUsedForCustomFilter(marketType);
                if (b && filterExtraWhere != null) b = filterExtraWhere.isUsed(marketType);
                return b;
            }
        };
        return filterCustomFilter;
    }
    
    public boolean isUsedForDataSourceFilter(MarketType marketType) {
        return true;
    }
    public boolean isUsedForCustomFilter(MarketType marketType) {
        return true;
    }
}
