// Generated by OABuilder
package test.xice.tsac.model.oa.propertypath;
 
import test.xice.tsac.model.oa.*;
 
public class GSMRWarningPP {
    private static GCIConnectionPPx gciConnection;
    private static GSMRServerPPx gsmrServer;
    private static GSRequestPPx gsRequest;
    private static WarningPPx warning;
     

    public static GCIConnectionPPx gciConnection() {
        if (gciConnection == null) gciConnection = new GCIConnectionPPx(GSMRWarning.P_GCIConnection);
        return gciConnection;
    }

    public static GSMRServerPPx gsmrServer() {
        if (gsmrServer == null) gsmrServer = new GSMRServerPPx(GSMRWarning.P_GSMRServer);
        return gsmrServer;
    }

    public static GSRequestPPx gsRequest() {
        if (gsRequest == null) gsRequest = new GSRequestPPx(GSMRWarning.P_GSRequest);
        return gsRequest;
    }

    public static WarningPPx warning() {
        if (warning == null) warning = new WarningPPx(GSMRWarning.P_Warning);
        return warning;
    }

    public static String id() {
        String s = GSMRWarning.P_Id;
        return s;
    }
}
 
