// Generated by OABuilder
package test.xice.tsac.model.oa.propertypath;
 
import test.xice.tsac.model.oa.*;
 
public class MRADServerCommandPP {
    private static AdminUserPPx adminUser;
    private static MRADClientCommandPPx mradClientCommands;
    private static MRADServerPPx mradServer;
    private static SSHExecutePPx sshExecute;
     

    public static AdminUserPPx adminUser() {
        if (adminUser == null) adminUser = new AdminUserPPx(MRADServerCommand.P_AdminUser);
        return adminUser;
    }

    public static MRADClientCommandPPx mradClientCommands() {
        if (mradClientCommands == null) mradClientCommands = new MRADClientCommandPPx(MRADServerCommand.P_MRADClientCommands);
        return mradClientCommands;
    }

    public static MRADServerPPx mradServer() {
        if (mradServer == null) mradServer = new MRADServerPPx(MRADServerCommand.P_MRADServer);
        return mradServer;
    }

    public static SSHExecutePPx sshExecute() {
        if (sshExecute == null) sshExecute = new SSHExecutePPx(MRADServerCommand.P_SSHExecute);
        return sshExecute;
    }

    public static String id() {
        String s = MRADServerCommand.P_Id;
        return s;
    }

    public static String created() {
        String s = MRADServerCommand.P_Created;
        return s;
    }

    public static String type() {
        String s = MRADServerCommand.P_Type;
        return s;
    }

    public static String started() {
        String s = MRADServerCommand.P_Started;
        return s;
    }

    public static String error() {
        String s = MRADServerCommand.P_Error;
        return s;
    }

    public static String console() {
        String s = MRADServerCommand.P_Console;
        return s;
    }

    public static String runOnMRADServer() {
        String s = "runOnMRADServer";
        return s;
    }
}
 
